services:
  db:
    image: mysql:8.0
    container_name: alxtravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: alxtravel
      MYSQL_USER: alxuser
      MYSQL_PASSWORD: alxpass
    ports:
      - "3308:3306"   # host:container
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

